_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.11.0
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
